name: Update Storybook from Figma
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 전체 Git 기록을 가져와서 package.json 누락 방지
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: ls -al  # 디버깅용 (package.json 위치 확인)
      - run: npm install
        working-directory: dsx-framework  # package.json이 있는 폴더 지정
      - run: echo "FIGMA_API_KEY is $FIGMA_API_KEY"
      - run: echo "FIGMA_FILE_ID is $FIGMA_FILE_ID"
      - run: node fetch-figma.js
        env:
          FIGMA_API_KEY: ${{ secrets.FIGMA_API_KEY }}
          FIGMA_FILE_ID: ${{ secrets.FIGMA_FILE_ID }}
      - run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add figmaComponents.json
          git commit -m "Update Figma components" || echo "No changes"
          git push
      - run: npm run build-storybook
        working-directory: dsx-framework  # package.json이 있는 폴더 지정
      - uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: storybook-static
